spring:
  datasource:
    url: jdbc:mysql://TODO:3306/trainings_prod
    username: trainings_prod
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: false